#global settings
global:
  logLevel: info
  splunk:
    hec:
      protocol: https
      insecureSSL: true
      host: splunk-cl01-indexer-service.splunk.svc.cluster.local
      token: 40e756ee-431d-4047-9db4-6b4a745472a1
      port: 8088

#local config for logging chart
splunk-kubernetes-logging:
  kubernetes:
    clusterName: cluster-5752
  journalLogPath: /var/log/journal
  serviceAccount:
    name: splunk-kubernetes-logging
  splunk:
    hec:
      indexName: em_events

#local config for objects chart
splunk-kubernetes-objects:
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-objects
  kubernetes:
    insecureSSL: true
    clusterName: cluster-5752
  objects:
    core:
      v1:
        [{"name":"pods", "interval":"60s"},{"name":"nodes", "interval":"60s"},{"name":"component_statuses", "interval":"60s"},{"name":"config_maps", "interval":"60s"},{"name":"namespaces", "interval":"60s"},{"name":"persistent_volumes", "interval":"60s"},{"name":"persistent_volume_claims", "interval":"60s"},{"name":"resource_quotas", "interval":"60s"},{"name":"services", "interval":"60s"},{"name":"service_accounts", "interval":"60s"},{"name":"events", "mode":"watch"},]
    apps:
      v1:
        [{"name":"daemon_sets", "interval":"60s"},{"name":"deployments", "interval":"60s"},{"name":"replica_sets", "interval":"60s"},{"name":"stateful_sets", "interval":"60s"},]
  splunk:
    hec:
      indexName: em_meta

#local config for metrics chart
splunk-kubernetes-metrics:
  metricsInterval: 60s
  kubernetes:
    kubeletAddress: "\"#{ENV['KUBERNETES_NODE_IP']}\""
    kubeletPort: 10250
    useRestClientSSL: true
    insecureSSL: true
    clusterName: cluster-5752
  rbac:
    create: true
  serviceAccount:
    create: true
    name: splunk-kubernetes-metrics
  splunk:
    hec:
      indexName: em_metrics
