---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/clusterRole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sck-rendered-splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    chart: splunk-kubernetes-objects-1.4.9
    release: sck-rendered
    heritage: Helm
rules:
  
  - apiGroups: [""]
    resources:
    - pods
    - nodes
    - componentstatuses
    - configmaps
    - namespaces
    - persistentvolumes
    - persistentvolumeclaims
    - resourcequotas
    - services
    - serviceaccounts
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
    - events
    verbs: ["watch"]
  - apiGroups: ["apps"]
    resources:
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    verbs: ["get", "list"]
