---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/clusterRoleBinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sck-rendered-splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    chart: splunk-kubernetes-objects-1.4.9
    release: sck-rendered
    heritage: Helm
roleRef:
  kind: ClusterRole
  name: sck-rendered-splunk-kubernetes-objects
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: splunk-kubernetes-objects
  namespace: splunk-connect
