apiVersion: enterprise.splunk.com/v1
kind: LicenseMaster 
metadata:
  name: lm01 
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  volumes:
    - name: licenses
      configMap:
        name: splunk-licenses
  licenseUrl: /mnt/licenses/enterprise.lic
