---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRoleAggregator.yaml
# This role allows read access to the kubelet summary API
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-api-aggregator
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.4.9
    release: sck-rendered
    heritage: Helm
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/stats
  - nodes/proxy
  - pods
  verbs:
  - get
  - list
