---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRole.yaml
# This role allows read access to the kubelet summary API
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubelet-summary-api-read
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.4.9
    release: sck-rendered
    heritage: Helm
rules:
- apiGroups:
  - ""
  resources:
  - "nodes"
  - "nodes/stats"
  - "nodes/metrics"
  verbs:
  - "get"
