---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sck-rendered-splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.4.9
    release: sck-rendered
    heritage: Helm
    engine: fluentd
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: sck-rendered-splunk-kubernetes-metrics
  template:
    metadata:
      name: sck-rendered-splunk-kubernetes-metrics
      labels:
        name: sck-rendered-splunk-kubernetes-metrics
        app: splunk-kubernetes-metrics
        chart: splunk-kubernetes-metrics-1.4.9
        release: sck-rendered
        heritage: Helm
        engine: fluentd
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/config: cfc721f9d65334b0b5b9010db553216c8c93c2b26825aacda8b8c6f9b9a99f03
    spec:
      serviceAccountName: splunk-kubernetes-metrics
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      containers:
      - name: splunk-fluentd-k8s-metrics
        image: docker.io/splunk/k8s-metrics:1.1.6
        imagePullPolicy: IfNotPresent
        env:
          - name: KUBERNETES_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: splunk-kubernetes-metrics
                key: splunk_hec_token
        resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 300Mi
        securityContext:
          runAsNonRoot: false
        volumeMounts:
          - name: conf-configmap
            mountPath: /fluentd/etc
          - name: secrets
            mountPath: /fluentd/etc/splunk
            readOnly: true
        livenessProbe:
          httpGet:
            path: /api/plugins.json
            port: 24220
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: conf-configmap
        configMap:
          name: sck-rendered-splunk-kubernetes-metrics
      - name: secrets
        secret:
          secretName: splunk-kubernetes-metrics
