---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sck-rendered-splunk-kubernetes-metrics-agg
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.4.9
    release: sck-rendered
    heritage: Helm
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: splunk-kubernetes-metrics
      release: sck-rendered
  template:
    metadata:
      labels:
        app: splunk-kubernetes-metrics
        release: sck-rendered
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/config: 16b1eeb6d2af68c4e9ce6b1edaabbf652747b8a969221054b006f19f8e796662
    spec:
      serviceAccountName: splunk-kubernetes-metrics
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: splunk-fluentd-k8s-metrics-agg
        image: docker.io/splunk/k8s-metrics-aggr:1.1.6
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
        env:
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: splunk-kubernetes-metrics
                key: splunk_hec_token
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 300Mi
        securityContext:
          runAsNonRoot: false
        volumeMounts:
          - name: conf-configmap
            mountPath: /fluentd/etc
          - name: secrets
            mountPath: /fluentd/etc/splunk
            readOnly: true
        livenessProbe:
          httpGet:
            path: /api/plugins.json
            port: 24220
          initialDelaySeconds: 60
          periodSeconds: 60
      volumes:
      - name: conf-configmap
        configMap:
          name: sck-rendered-splunk-kubernetes-metrics-aggregator
      - name: secrets
        secret:
          secretName: splunk-kubernetes-metrics
