---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: splunk-kubernetes-logging
  labels:
    app: splunk-kubernetes-logging
    chart: splunk-kubernetes-logging-1.4.9
    release: sck-rendered
    heritage: Helm
type: Opaque
data:
  splunk_hec_token: NDBlNzU2ZWUtNDMxZC00MDQ3LTlkYjQtNmI0YTc0NTQ3MmEx
