---
# Source: splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-kubernetes-logging
  labels:
    app: splunk-kubernetes-logging
    chart: splunk-kubernetes-logging-1.4.9
    release: sck-rendered
    heritage: Helm
